Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "Sonarqube"
    config.vm.network "private_network", ip: "192.168.56.11" 
    config.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1" 
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider "virtualbox" do |v|
        v.name = 'Sonarqube'
        v.memory = 4096
        v.cpus = 2
    end
end